### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by liblit** [p3lim/feedly-counter#1]
Feedly now supports [HTTPS for all users](http://blog.feedly.com/2013/08/26/feedly-pro-available-for-all/), both free ("standard") and paid ("pro"). The feedly-counter extension should use HTTPS instead of HTTP, or at least offer an option to pick between the two. This should apply to internal network traffic when checking for unread articles. It should also affect the destination used when the extension is clicked on: https://cloud.feedly.com/ instead of http://cloud.feedly.com/. Thank you!

**Comment by p3lim** [comment]
298fb07b119e2b8207534764bd41073cf89fcad7
