### ISSUE TITLE
Grey icon as of ~1hour ago

### ISSUE THREAD

**Issue by ramenchef** [p3lim/feedly-counter#4]
Something happened, maybe on the backend of feedly, that has caused this extension to stop working.  I've tried reinstalling the extension as well as restarting chrome. Enabling the beta of feedly didn't help either.

**Comment by p3lim** [comment]
I'm aware of the issue and I will resolve it as soon as I can.
As a temporary way to solve it before I get to it (one-time deal), you can follow these steps:
1. Open up the options for the extension
2. Hit Ctrl+Shift+J (or Cmd+Optn+J on OSX) to open developer console
3. Select "Resources" tab
4. In the tree on the left, expand "Local Storage" and click the first child
5. Select all the lines on the right (drag works well, if not, do select one by one and the next step for each)
6. Press delete (or right-click and select delete)

This is the way to delete all settings and variables for the extension, and should resolve any issues.

**Comment by ramenchef** [comment]
This issue is popped back up as of today. Clearing local storage does not fix it either.

**Comment by p3lim** [comment]
I stopped using Feedly as they wanted to throttle the release API keys, and I did not get one, and as such, I discontinued this project in favor of using Digg.com's Reader.

**Comment by WORMSS** [comment]
I have removed the variables, and now it takes me to null://feedly.com/ and of course does not work now.

**Comment by p3lim** [comment]
You have to reload the extension (or restart chrome) after clearing out the settings manually.

In any case, I am no longer using Feedly for my RSS needs, so I won't be updating this extension any more.
