### ISSUE TITLE
Stopped working after last update

### ISSUE THREAD

**Issue by ghost** [p3lim/feedly-counter#5]
After last update, it only shows a grey icon with a question mark. :-( Tried different setting HTTPS on/off, BETA on/off, no changes.

**Comment by p3lim** [comment]
It's an issue with the authentication token, and this is temporarily fixable as described in issue #4.
This will be properly resolved as soon as I get my API certificate from Feedly (no ETA), see issue #3.

**Comment by ghost** [comment]
Ok, worked :-)
Thanks

**Comment by p3lim** [comment]
The bug causing this still exists, so until then this issue will remain open.
